### ISSUE TITLE
Lock screen is too dim when recieving a notification

### ISSUE THREAD

**Issue by selimsum** [iamthecloverly/android_device_realme_RM6785#2]
Device: Realme 6
Tested ROMs: PixelPlusUI 5.1, PixelExtended Plus 13.0 and ArrowOS 13.0 (probably all Pixel based ROMs are affected)

This issue was already reported [here](https://www.reddit.com/r/GooglePixel/comments/u9is8i/pixel_6_notifications_on_lock_screen_are_very_dim/) as a Pixel issue, but is also seems to be affecting customs ROMs. Not sure if it's possible to fix, but I'm reporting for you to take a look at.

**Comment by iamthecloverly** [comment]
Hello @selimsumlu,
Thank you for reporting the issue. As you mentioned that the issue was already reported [here](https://www.reddit.com/r/GooglePixel/comments/u9is8i/pixel_6_notifications_on_lock_screen_are_very_dim/) as a Pixel issue, it'll affect custom ROMs also, because of the fact that all the custom ROMs are based on Google's AOSP.
This issue can be fixed only if google fixes this on their pixel devices.
